package napredno.programiranje.view.form;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import napredno.programiranje.communication.Communication;
import napredno.programiranje.domain.User;

public class FrmMain extends JFrame {

	private User user;

    public FrmMain(User user) {
        initComponents();
        //setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        this.user = user;
        lblUser.setText("Prijavljen korisnik: " + user.getFirstName() + " " + user.getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAddProduct = new javax.swing.JMenuItem();
        miProductView = new javax.swing.JMenuItem();
        itemCustomer = new javax.swing.JMenu();
        itemAddCustomer = new javax.swing.JMenuItem();
        miViewCustomers = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        miInvoiceView = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemLogOutNewLogin = new javax.swing.JMenuItem();
        itemLogOutExit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavni meni");

        lblUser.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblUser.setText("Prijavljen korisnik:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dobro došli!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Izaberite neku od opcija iz menija.");

        jMenu1.setText("Proizvod");

        itemAddProduct.setText("Dodaj");
        itemAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddProductActionPerformed(evt);
            }
        });
        jMenu1.add(itemAddProduct);

        miProductView.setText("Prikaz");
        miProductView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductViewActionPerformed(evt);
            }
        });
        jMenu1.add(miProductView);

        jMenuBar1.add(jMenu1);

        itemCustomer.setText("Kupac");

        itemAddCustomer.setText("Dodaj");
        itemAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddCustomerActionPerformed(evt);
            }
        });
        itemCustomer.add(itemAddCustomer);

        miViewCustomers.setText("Prikaz");
        miViewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miViewCustomersActionPerformed(evt);
            }
        });
        itemCustomer.add(miViewCustomers);

        jMenuBar1.add(itemCustomer);

        jMenu2.setText("Faktura");

        jMenuItem7.setText("Dodaj");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        miInvoiceView.setText("Prikaz");
        miInvoiceView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInvoiceViewActionPerformed(evt);
            }
        });
        jMenu2.add(miInvoiceView);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Odjava");

        itemLogOutNewLogin.setText("Odjava i nova prijava");
        itemLogOutNewLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogOutNewLoginActionPerformed(evt);
            }
        });
        jMenu3.add(itemLogOutNewLogin);

        itemLogOutExit.setText("Odjava i izlazak iz aplikacije");
        itemLogOutExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogOutExitActionPerformed(evt);
            }
        });
        jMenu3.add(itemLogOutExit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void itemLogOutNewLoginActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        int number = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da se odjavite sa aplikacije?", "Odjava", JOptionPane.YES_NO_OPTION);
        if (number == 0) {
            try {
                String str = Communication.getInstance().logout();
                JOptionPane.showMessageDialog(this, str);
                this.dispose();
                new FrmLogin().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                                  

    private void itemLogOutExitActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int number = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da se odjavite sa aplikacije?", "Odjava", JOptionPane.YES_NO_OPTION);
        if (number == 0) {
            try {
                String str = Communication.getInstance().logout();
                JOptionPane.showMessageDialog(this, str);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                              

    private void itemAddProductActionPerformed(java.awt.event.ActionEvent evt) {                                               
        new FrmAddEditProduct(this, rootPaneCheckingEnabled).setVisible(true);
    }                                              

    private void itemAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                                
        new FrmAddEditCustomer(this, rootPaneCheckingEnabled).setVisible(true);
    }                                               

    private void miViewCustomersActionPerformed(java.awt.event.ActionEvent evt) {                                                
        new FrmViewCustomers().setVisible(true);
    }                                               

    private void miProductViewActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new FrmViewProducts().setVisible(true);
    }                                             

    private void miInvoiceViewActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new FrmViewInvoices().setVisible(true);
    }                                             

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        new FrmAddInvoice().setVisible(true);
    }                                          

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem itemAddCustomer;
    private javax.swing.JMenuItem itemAddProduct;
    private javax.swing.JMenu itemCustomer;
    private javax.swing.JMenuItem itemLogOutExit;
    private javax.swing.JMenuItem itemLogOutNewLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem miInvoiceView;
    private javax.swing.JMenuItem miProductView;
    private javax.swing.JMenuItem miViewCustomers;
    // End of variables declaration                   
}
